### ISSUE TITLE
Maximum secret size only 4032 bytes

### ISSUE THREAD

**Issue by haraldh** [enarx-archive/sev#35] opened 2020-11-26 12:50 UTC
According to my experiments, the maximum secret size, which can be injected without `EINVAL`
```
ioctl(5, KVM_MEMORY_ENCRYPT_OP, 0x7fff4268c3a8) = -1 EINVAL (Invalid argument)
```
seems to be 4032. Curious why it is 4096 - 64 ... and if it is a SEV limitation or kernel limitation or kernel bug.

**Comment by connorkuehl** [comment] 2020-12-02 15:45
@codomania Is this something you've run into before?

**Comment by codomania** [comment] 2020-12-02 16:00
IIRC, the only restriction that kernel puts is that the guest_uaddr + length should not cross a page boundary. So, if the length of the blob is a PAGE_SIZE then you must ensure that guest_uaddr is page-aligned otherwise we may start in the middle of the page blob may cross the page boundry.

**Comment by connorkuehl** [comment] 2020-12-02 16:06
> IIRC, the only restriction that kernel puts is that the guest_uaddr + length should not cross a page boundary. So, if the length of the blob is a PAGE_SIZE then you must ensure that guest_uaddr is page-aligned otherwise we may start in the middle of the page blob may cross the page boundry.

In that case since the firmware supports secrets up to 16KiB in length, then I presume our process needs to be using at least a 2MiB page to reach that firmware-supported maximum without the kernel returning an error from the ioctl?

**Comment by codomania** [comment] 2020-12-02 16:38
Yes, I think that should work fine. Allocate 2MiB page, fill the data from offset zero to 16KiB in the length. Issue the launch_secret command.

**Comment by connorkuehl** [comment] 2021-08-16 18:34
Closing, since this is not a bug. The calling process that is using this crate will need to use larger pages if it wants to inject a secret larger than 4032 bytes.

**Closed as completed by connorkuehl** 2021-08-16 18:34 UTC
